import '../../flutter_flow/flutter_flow_util.dart';

import 'api_manager.dart';

export 'api_manager.dart' show ApiCallResponse;

const _kPrivateApiFunctionName = 'ffPrivateApiCall';

class AccessPointCall {
  static Future<ApiCallResponse> call({
    String? route = '',
    String? name = '',
    String? surname = '',
    String? phone = '',
    String? email = '',
    String? country = '',
    String? userType = '',
    String? points = '',
    String? refId = '',
    String? walletAmount = '',
    String? walletId = '',
    String? customerId = '',
    String? paymentMethod = '',
    String? uid = '',
    String? currency = '',
    String? description = '',
    bool? capture = true,
    String? type = '',
    String? cardNumber = '',
    String? expirationMonth = '',
    String? expirationYear = '',
    String? cardHolder = '',
    String? cvv = '',
    String? identificationValue = '',
    String? accountNumber = '',
    String? beneficiaryId = '',
    String? beneficiaryCountry = '',
    String? payoutCurrency = '',
    String? planId = '',
    String? months = '',
    String? interest = '',
    String? amount = '',
    String? totalRepayment = '',
    String? productId = '',
    String? ipiId = '',
    String? maxPayout = '',
    String? monthlyPayment = '',
    String? interval = '',
    bool? hasPayout,
    String? collectCardId = '',
    String? currentlyViewing = '',
    String? collectionName = '',
    String? checkoutType = '',
  }) {
    final body = '''
{
  "checkout_type": "${checkoutType}",
  "collection_name": "${collectionName}",
  "currently_viewing": "${currentlyViewing}",
  "collect_card_id": "${collectCardId}",
  "has_payout": ${hasPayout},
  "interval": "${interval}",
  "monthly_payment": "${monthlyPayment}",
  "route": "${route}",
  "name": "${name}",
  "surname": "${surname}",
  "phone": "${phone}",
  "email": "${email}",
  "country": "${country}",
  "user_type": "${userType}",
  "points": "${points}",
  "ref_id": "${refId}",
  "wallet_amount": "${walletAmount}",
  "wallet_id": "${walletId}",
  "customer_id": "${customerId}",
  "payment_method": "${paymentMethod}",
  "uid": "${uid}",
  "currency": "${currency}",
  "description": "${description}",
  "capture": "${capture}",
  "type": "${type}",
  "card_number": "${cardNumber}",
  "expiration_month": "${expirationMonth}",
  "expiration_year": "${expirationYear}",
  "card_holder": "${cardHolder}",
  "cvv": "${cvv}",
  "identification_value": "${identificationValue}",
  "account_number": "${accountNumber}",
  "beneficiary_id": "${beneficiaryId}",
  "beneficiary_country": "${beneficiaryCountry}",
  "payout_currency": "${payoutCurrency}",
  "plan_id": "${planId}",
  "months": "${months}",
  "interest": "${interest}",
  "amount": "${amount}",
  "product_id": "${productId}",
  "total_repayment": "${totalRepayment}",
  "ipi_id": "${ipiId}",
  "max_payout": "${maxPayout}"
}''';
    return ApiManager.instance.makeApiCall(
      callName: 'Access Point',
      apiUrl: 'https://explravenue.com/kreative/api/accesspoint/post',
      callType: ApiCallType.POST,
      headers: {},
      params: {},
      body: body,
      bodyType: BodyType.JSON,
      returnBody: true,
    );
  }
}
